## nn module

In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# forward pass
model(features)

tensor([[0.5499],
        [0.6091],
        [0.6182],
        [0.5669],
        [0.5917],
        [0.6142],
        [0.6101],
        [0.5593],
        [0.5887],
        [0.5426]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.3718,  0.1404,  0.3764, -0.0195, -0.0153]], requires_grad=True)

In [4]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2970], requires_grad=True)

In [5]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [6]:
# Creating a model with hidden layers

class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out

In [7]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# forward pass
model(features)

tensor([[0.5226],
        [0.5245],
        [0.5260],
        [0.5220],
        [0.5225],
        [0.5236],
        [0.5195],
        [0.5242],
        [0.5214],
        [0.5202]], grad_fn=<SigmoidBackward0>)

In [8]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2519,  0.4219,  0.1773, -0.3350, -0.0835],
        [-0.0609, -0.2095, -0.1032, -0.1461,  0.0102],
        [ 0.3039, -0.0694, -0.3239, -0.0459, -0.3304]], requires_grad=True)

In [9]:
model.linear1.bias

Parameter containing:
tensor([ 0.4422, -0.3527,  0.0350], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[-0.0509,  0.4154,  0.1661]], requires_grad=True)

In [11]:
model.linear2.bias

Parameter containing:
tensor([0.1276], requires_grad=True)

In [12]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
# Creating a model with hidden layers using Sequential

class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid(),
        )

    def forward(self, features):

        out = self.network(features)
        
        return out

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3964749429.py, line 8)