# Tensors
Tensors are data structures used to store higher dimensional array designed for mathematical and computational efficiency.

Dimension -> In how many direction data is spanned.

1. Scalars: 0-dimensional tensors (Represents a single value, often used for simple matrics or constants)
2. Vectors: 1-dimensional tensors (Represents a sequence or a collection of values, e.g. Feature Vector-each word in a sentence maybe represented as a 1D vector using embeddings)
3. Matrics: 2D tensions (Represents tabular or grid like data)
4. 3D Tensors: Adds a third dimension, often used for stacking data e.g. RGB images(256X256 - shape: [256,256,3])
5. 4D Tensors: Batches of RGB images (Adds the batch size as an additional dimension to 3D data e.g dataset of colored image: (batch size X width X height X channels))
6. 5D Tensors: Video Data (Adds a time dimension for data that changes over time e.g, video frames)

## Why are Tensors Useful?
1. Mathematical Operations - enables efficient mathematical computations like addition, multiplication, dot product, etc.
2. Real world data representation 
3. Efficient computations

## Why are Tensors used in Deep Learning?
1. Storing data
2. Weights and Biases
3. Matrix Operations

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU not vailable. Using CPU")

GPU is available
Using GPU:NVIDIA GeForce RTX 4090


Creating Tensors

In [5]:
# Using Empty
#(row, column)
a = torch.empty(2,3)

In [6]:
#Check type
type(a)

torch.Tensor

In [7]:
#Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#Using rand
torch.rand(2,3)

tensor([[0.0839, 0.2669, 0.5163],
        [0.2003, 0.0023, 0.8190]])

In [10]:
#Use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
#Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
#A range
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [14]:
#Using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
#using eye - identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
#Using full - matrix of same value
torch.full((2,3), 42)

tensor([[42, 42, 42],
        [42, 42, 42]])