# Tensors
Tensors are data structures used to store higher dimensional array designed for mathematical and computational efficiency.

Dimension -> In how many direction data is spanned.

1. Scalars: 0-dimensional tensors (Represents a single value, often used for simple matrics or constants)
2. Vectors: 1-dimensional tensors (Represents a sequence or a collection of values, e.g. Feature Vector-each word in a sentence maybe represented as a 1D vector using embeddings)
3. Matrics: 2D tensions (Represents tabular or grid like data)
4. 3D Tensors: Adds a third dimension, often used for stacking data e.g. RGB images(256X256 - shape: [256,256,3])
5. 4D Tensors: Batches of RGB images (Adds the batch size as an additional dimension to 3D data e.g dataset of colored image: (batch size X width X height X channels))
6. 5D Tensors: Video Data (Adds a time dimension for data that changes over time e.g, video frames)

## Why are Tensors Useful?
1. Mathematical Operations - enables efficient mathematical computations like addition, multiplication, dot product, etc.
2. Real world data representation 
3. Efficient computations

## Why are Tensors used in Deep Learning?
1. Storing data
2. Weights and Biases
3. Matrix Operations

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU not vailable. Using CPU")

GPU is available
Using GPU:NVIDIA GeForce RTX 4090


Creating Tensors

In [3]:
# Using Empty
#(row, column)
a = torch.empty(2,3)

In [4]:
#Check type
type(a)

torch.Tensor

In [5]:
#Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#Using rand
torch.rand(2,3)

tensor([[0.0617, 0.4587, 0.2069],
        [0.5290, 0.8794, 0.4936]])

In [8]:
#Use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
#Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#A range
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [11]:
#Using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
#using eye - identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
#Using full - matrix of same value
torch.full((2,3), 42)

tensor([[42, 42, 42],
        [42, 42, 42]])

Tesnor shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[4429604587376,             0,             0],
        [            0,             0,             0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Tesnor Data Types

In [21]:
#Find data type
x.dtype

torch.int64

In [22]:
#assign data type
i = torch.tensor([1,2,3], dtype=torch.int32)
f = torch.tensor([1,2,3], dtype=torch.float64)
print(i,f)
print(i.dtype,f.dtype)

tensor([1, 2, 3], dtype=torch.int32) tensor([1., 2., 3.], dtype=torch.float64)
torch.int32 torch.float64


In [23]:
#using to() to change data type
i.to(torch.float32)

tensor([1., 2., 3.])

# Mathematical Operations

1. Scalar operation

In [25]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [27]:
# addition
x+2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [28]:
# subtraction
x-1

tensor([[-0.1306, -0.4323],
        [-0.2589, -0.5706]])

In [29]:
# multiplication
x*3

tensor([[2.6082, 1.7031],
        [2.2233, 1.2882]])

In [30]:
# division
x/3

tensor([[0.2898, 0.1892],
        [0.2470, 0.1431]])

In [31]:
#int division
(x*100)//3

tensor([[28., 18.],
        [24., 14.]])

In [32]:
# mod
((x*100)//3)%5

tensor([[3., 3.],
        [4., 4.]])

In [33]:
# power
x**3

tensor([[0.6572, 0.1830],
        [0.4070, 0.0792]])

2. Element Wise Operation

In [34]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a,b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]]) tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [35]:
a+b

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

In [36]:
a-b

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

In [37]:
a*b

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

In [38]:
a/b

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

In [39]:
a**b

tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])

In [40]:
a%b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [41]:
c = torch.tensor([1,-2,3,-4])

In [42]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d = torch.tensor([1.4,2.7,3.5,4.3])

In [45]:
torch.round(d)

tensor([1., 3., 4., 4.])

In [46]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.7000, 3.5000, 4.0000])

3. Reduction Operation

In [49]:
e = torch.randint(size=(3,4), low=0, high=10)
e

tensor([[7, 9, 2, 0],
        [5, 9, 3, 4],
        [9, 6, 2, 0]])

In [50]:
torch.sum(e)   #sum of all elements

tensor(56)

In [51]:
torch.sum(e, dim=0)  #sum of each column

tensor([21, 24,  7,  4])

In [52]:
torch.sum(e, dim=1)  #sum of each row

tensor([18, 21, 17])

In [54]:
f = torch.randint(size=(3,4), low=0, high=10, dtype=torch.float32)

In [55]:
torch.mean(f)   #mean of all elements

tensor(5.)

In [56]:
torch.mean(f, dim=0)  #mean of each column

tensor([5.3333, 4.0000, 3.3333, 7.3333])

In [57]:
torch.mean(f, dim=1)  #mean of each row

tensor([6.0000, 4.2500, 4.7500])

In [58]:
torch.median(f)   #median of all elements

tensor(4.)

In [59]:
torch.max(f)   #max of all elements

tensor(9.)

In [60]:
torch.min(f)   #min of all elements

tensor(0.)

In [61]:
torch.prod(f)   #product of all elements

tensor(0.)

In [62]:
torch.std(f)   #standard deviation of all elements

tensor(2.8920)

In [63]:
torch.var(f)   #variance of all elements

tensor(8.3636)

In [64]:
torch.argmax(f)   #index of max element

tensor(3)

In [65]:
torch.argmin(f)   #index of min element

tensor(10)

4. Matrix operations

In [67]:
g = torch.randint(size=(3,4), low=0, high=10)
h = torch.randint(size=(4,3), low=0, high=10)
print(g,h)

tensor([[3, 7, 8, 1],
        [4, 1, 6, 3],
        [2, 0, 9, 8]]) tensor([[5, 3, 7],
        [7, 5, 9],
        [1, 5, 1],
        [9, 1, 4]])


In [68]:
torch.mm(g,h)   #matrix multiplication

tensor([[81, 85, 96],
        [60, 50, 55],
        [91, 59, 55]])

In [69]:
torch.matmul(g,h)   #matrix multiplication

tensor([[81, 85, 96],
        [60, 50, 55],
        [91, 59, 55]])

In [70]:
torch.dot(torch.tensor([1,2,3]), torch.tensor([4,5,6]))   #dot product

tensor(32)

In [71]:
torch.transpose(g, 0, 1)   #transpose

tensor([[3, 4, 2],
        [7, 1, 0],
        [8, 6, 9],
        [1, 3, 8]])

In [72]:
k = torch.randint(size=(4,4), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 3., 7., 5.],
        [7., 1., 5., 7.],
        [5., 8., 5., 4.],
        [1., 1., 0., 9.]])

In [73]:
torch.det(k)   #determinant

tensor(2897.9998)

In [74]:
torch.inverse(k)   #inverse

tensor([[-0.1139,  0.1263,  0.0331, -0.0497],
        [-0.0259, -0.1077,  0.1439,  0.0342],
        [ 0.1429,  0.0476, -0.0476, -0.0952],
        [ 0.0155, -0.0021, -0.0197,  0.1128]])

5. Comparison operations

In [75]:
m = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
n = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(m,n)

tensor([[0., 9., 1.],
        [8., 9., 6.],
        [7., 6., 0.]]) tensor([[9., 5., 2.],
        [9., 1., 7.],
        [8., 6., 0.]])


In [76]:
m > n

tensor([[False,  True, False],
        [False,  True, False],
        [False, False, False]])

In [77]:
m < n

tensor([[ True, False,  True],
        [ True, False,  True],
        [ True, False, False]])

In [78]:
m == n

tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True]])

In [79]:
m != n

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False, False]])

6. Special Functions

In [80]:
o = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [81]:
torch.log(o)

tensor([[1.7918, 2.0794, 1.7918],
        [2.0794,   -inf, 1.7918],
        [2.1972,   -inf, 1.6094]])

In [82]:
torch.exp(o)

tensor([[4.0343e+02, 2.9810e+03, 4.0343e+02],
        [2.9810e+03, 1.0000e+00, 4.0343e+02],
        [8.1031e+03, 1.0000e+00, 1.4841e+02]])

In [83]:
torch.sqrt(o)

tensor([[2.4495, 2.8284, 2.4495],
        [2.8284, 0.0000, 2.4495],
        [3.0000, 0.0000, 2.2361]])

In [84]:
torch.sigmoid(o)

tensor([[0.9975, 0.9997, 0.9975],
        [0.9997, 0.5000, 0.9975],
        [0.9999, 0.5000, 0.9933]])

In [85]:
torch.softmax(o, dim=0)

tensor([[3.5119e-02, 9.9933e-01, 4.2232e-01],
        [2.5950e-01, 3.3524e-04, 4.2232e-01],
        [7.0538e-01, 3.3524e-04, 1.5536e-01]])

In [86]:
torch.relu(o)

tensor([[6., 8., 6.],
        [8., 0., 6.],
        [9., 0., 5.]])

In [87]:
torch.tanh(o)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 0.9999]])

7. Inplace Operations

In [88]:
p = torch.rand(3,3)
q = torch.rand(3,3)
print(p,q)

tensor([[0.1330, 0.4137, 0.6044],
        [0.7581, 0.9037, 0.9555],
        [0.1035, 0.6258, 0.2849]]) tensor([[0.4452, 0.1258, 0.9554],
        [0.1330, 0.7672, 0.6757],
        [0.6625, 0.2297, 0.9545]])


In [90]:
p+q

tensor([[0.5782, 0.5394, 1.5599],
        [0.8912, 1.6709, 1.6312],
        [0.7660, 0.8555, 1.2394]])

In [91]:
p.add_(q)

tensor([[0.5782, 0.5394, 1.5599],
        [0.8912, 1.6709, 1.6312],
        [0.7660, 0.8555, 1.2394]])

In [92]:
p

tensor([[0.5782, 0.5394, 1.5599],
        [0.8912, 1.6709, 1.6312],
        [0.7660, 0.8555, 1.2394]])

In [93]:
q

tensor([[0.4452, 0.1258, 0.9554],
        [0.1330, 0.7672, 0.6757],
        [0.6625, 0.2297, 0.9545]])

In [95]:
p.relu_()

tensor([[0.5782, 0.5394, 1.5599],
        [0.8912, 1.6709, 1.6312],
        [0.7660, 0.8555, 1.2394]])

Copying a tensor

In [96]:
a = torch.rand(3,3)
a

tensor([[0.6099, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]])

In [97]:
b = a

In [98]:
b

tensor([[0.6099, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]])

In [99]:
a[0][0] = 0

In [100]:
b

tensor([[0.0000, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]])

In [101]:
id(a)

2127061571680

In [102]:
id(b)

2127061571680

In [103]:
b = a.clone()

In [104]:
a

tensor([[0.0000, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]])

In [105]:
b

tensor([[0.0000, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]])

In [106]:
a[0][0] = 2

In [109]:
a
print(id(a))

2127061571680


In [110]:
id(b)

2127061740000

Tensor Operation on GPU

In [111]:
torch.cuda.is_available()

True

In [112]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [113]:
torch.rand(2,2).to(device)

tensor([[0.2469, 0.4761],
        [0.7792, 0.3722]], device='cuda:0')

In [114]:
b.to(device)

tensor([[0.0000, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709],
        [0.9295, 0.6115, 0.2234]], device='cuda:0')

In [116]:
import time
import torch

In [117]:
size = 10000

In [118]:
mat1_cpu = torch.randn(size, size)
mat2_cpu = torch.randn(size, size)

In [119]:
start_time = time.time()
result_cpu = torch.matmul(mat1_cpu, mat2_cpu)
cpu_time = time.time() - start_time
print(f"CPU time: {cpu_time} seconds")

CPU time: 1.300119161605835 seconds


In [120]:
#Move to GPU
mat1_gpu = mat1_cpu.to(device)
mat2_gpu = mat2_cpu.to(device)

start_time = time.time()
result_gpu = torch.matmul(mat1_gpu, mat2_gpu)
torch.cuda.synchronize() #wait for all GPU operations to finish
gpu_time = time.time() - start_time
print(f"GPU time: {gpu_time} seconds")

GPU time: 0.4062027931213379 seconds


In [121]:
#Compare results
print("\nSpeedUp: ", cpu_time/gpu_time)


SpeedUp:  3.2006652431301057


# Reshaping Tensors

In [122]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [124]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
b = torch.rand(2,3,4)
b

tensor([[[0.9983, 0.4222, 0.2836, 0.2199],
         [0.4636, 0.6804, 0.0093, 0.2360],
         [0.1814, 0.1750, 0.4011, 0.0637]],

        [[0.3615, 0.9939, 0.6543, 0.3914],
         [0.8772, 0.7846, 0.2483, 0.6182],
         [0.6249, 0.3300, 0.4929, 0.4224]]])

In [127]:
b.permute(2,0,1)

tensor([[[0.9983, 0.4636, 0.1814],
         [0.3615, 0.8772, 0.6249]],

        [[0.4222, 0.6804, 0.1750],
         [0.9939, 0.7846, 0.3300]],

        [[0.2836, 0.0093, 0.4011],
         [0.6543, 0.2483, 0.4929]],

        [[0.2199, 0.2360, 0.0637],
         [0.3914, 0.6182, 0.4224]]])

In [128]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [129]:
#Unsqueeze
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [134]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])